name: ecommerce_churn_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - pandas
      - numpy
      - scikit-learn
      - joblib
      - matplotlib